"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!rcr$z=_!7g(5f=05!^n_@g0bo2-wposgwolxo))f8=8r$#2d3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_bootstrap5',
    'django_ckeditor_5',
    'rest_framework',
    "drf_spectacular",
    "drf_spectacular_sidecar",

    'webapp',
    'accounts',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'defaultdb',
#         'USER': 'doadmin',
#         'PASSWORD': 'AVNS_3ii1Vy6NAc-bynqJxxe',
#         'HOST': 'lms-db-do-user-13656028-0.c.db.ondigitalocean.com',
#         'PORT': '25060',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'lms',
        'USER': 'lms_user',
        'PASSWORD': 'lms_password',
        'HOST': '185.22.67.9',
        'PORT': '5432',
    }
}
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://redis:6379/1',  # Используйте имя сервиса Redis
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGES = [
    ('en', _('English')),
    ('ru', _('Russian')),
]

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

# Включение интернационализации
USE_I18N = True
# Включение локализации
USE_L10N = True

USE_TZ = True

# Пути для файлов перевода
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/uploads/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'
LOGIN_URL = 'login'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.CustomUser'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Settings for CKEditor

CKEDITOR_5_FILE_STORAGE = "core.storage.CustomStorage"

customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "imageUpload"
        ],
    },
    "comment": {
        "language": {"ui": "en", "content": "en"},
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
        ],
    },
    "extends": {
        "language": "en",
        "blockToolbar": [
            "paragraph",
            "heading1",
            "heading2",
            "heading3",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote",
        ],
        "toolbar": [
            "heading",
            "codeBlock",
            "|",
            "outdent",
            "indent",
            "|",
            "bold",
            "italic",
            "link",
            "underline",
            "strikethrough",
            "code",
            "subscript",
            "superscript",
            "highlight",
            "|",
            "bulletedList",
            "numberedList",
            "todoList",
            "|",
            "blockQuote",
            "insertImage",
            "|",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            "mediaEmbed",
            "removeFormat",
            "insertTable",
            "sourceEditing",
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:side",
                "|",
                "toggleImageCaption",
                "|"
            ],
            "styles": [
                "full",
                "side",
                "alignLeft",
                "alignRight",
                "alignCenter",
            ],
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties",
            ],
            "tableProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
            "tableCellProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "Paragraph",
                    "class": "ck-heading_paragraph",
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "Heading 1",
                    "class": "ck-heading_heading1",
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "Heading 2",
                    "class": "ck-heading_heading2",
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "Heading 3",
                    "class": "ck-heading_heading3",
                },
            ]
        },
        "list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True,
            }
        },
        "htmlSupport": {
            "allow": [
                {"name": "/.*/", "attributes": True, "classes": True, "styles": True}
            ]
        },
    },
}

IOKA_SECRET_KEY = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJleHAiOjE4MzY2NDM3NDQsImlhdCI6MTcxNjQ0ODg5MCwiYXpwIjoiZGFzaGJvYXJkIiwiaXNzIjoiZ2FybWl1cyIsInN1YiI6InVzcl9VVE5EWFoyQkhOIiwiYXVkIjpbImFjY291bnQiLCJvcmdhbml6YXRpb24iLCJnYXJtaXVzIiwidHJhbnNmZXIiLCJyZXBvcnRzIiwiY3VzdG9tZXIiLCJtYXN0ZXJwYXNzIiwicGF5b3V0cyIsImNvcmUiXSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsid2FsbGV0cy5ldmVudHM6cmVhZCIsInRyYW5zZmVyczpyZWFkIiwicmVzb3VyY2VzOnJlYWQiLCJ3aXRoZHJhd2FsczpyZWFkIiwid2FsbGV0cy53ZWJob29rczp3cml0ZSIsIndhbGxldHMud2ViaG9va3M6cmVtb3ZlIiwid2FsbGV0cy53ZWJob29rczpyZWFkIiwid2FsbGV0czp3cml0ZSIsIndhbGxldHM6cmVtb3ZlIiwid2FsbGV0czpyZWFkIiwid2FsbGV0cy53Mnc6d3JpdGUiLCJ3YWxsZXRzLncydzpyZWFkIiwid2FsbGV0cy5hY2NvdW50OnJlYWQiLCJhY2NvdW50czp3cml0ZSIsImFjY291bnRzOnJlYWQiLCJ3YWxsZXRzLnRyYW5zYWN0aW9uczp3cml0ZSIsIndhbGxldHMudHJhbnNhY3Rpb25zOnJlbW92ZSIsIndhbGxldHMudHJhbnNhY3Rpb25zOnJlYWQiLCJkZXBvc2l0czp3cml0ZSIsImRlcG9zaXRzOnJlYWQiXX0sIm9yZ2FuaXphdGlvbiI6eyJyb2xlcyI6WyJvcmdhbml6YXRpb25zOndyaXRlIiwib3JnYW5pemF0aW9uczpyZW1vdmUiLCJvcmdhbml6YXRpb25zOnJlYWQiXX0sImdhcm1pdXMiOnsicm9sZXMiOlsic2hvcHMuc3ViOndyaXRlIl19LCJ0cmFuc2ZlciI6eyJyb2xlcyI6WyJ0cmFuc2Zlci1vcmRlcnM6d3JpdGUiLCJ0cmFuc2Zlci1vcmRlcnM6cmVhZCIsImNvcnAtY2FyZHM6d3JpdGUiLCJjb3JwLWNhcmRzOnJlYWQiXX0sInJlcG9ydHMiOnsicm9sZXMiOlsicmVwb3J0czpyZWFkIiwicmVwb3J0cy5wYXlvdXRzOndyaXRlIiwicmVwb3J0cy5wYXlvdXRzOnJlYWQiXX0sImN1c3RvbWVyIjp7InJvbGVzIjpbImN1c3RvbWVyczp3cml0ZSIsImN1c3RvbWVyczpyZWFkIiwiY3VzdG9tZXJzLiouY2FyZHM6d3JpdGUiLCJjdXN0b21lcnMuKi5jYXJkczpyZWFkIl19LCJtYXN0ZXJwYXNzIjp7InJvbGVzIjpbIm1hc3RlcnBhc3Muc2Vzc2lvbnM6d3JpdGUiLCJtYXN0ZXJwYXNzLnNlc3Npb25zOnJlYWQiLCJtYXN0ZXJwYXNzLnBob25lczp3cml0ZSIsIm1hc3RlcnBhc3MuY2FyZHM6d3JpdGUiLCJtYXN0ZXJwYXNzLmNhcmRzOnJlbW92ZSIsIm1hc3RlcnBhc3MuY2FyZHM6cmVhZCJdfSwicGF5b3V0cyI6eyJyb2xlcyI6WyJyZWNlaXZlcnM6d3JpdGUiLCJyZWNlaXZlcnM6cmVhZCIsInBheW91dC1vcmRlcnM6d3JpdGUiLCJwYXlvdXQtb3JkZXJzOnJlYWQiLCJwYXlvdXQtd2ViaG9va3M6d3JpdGUiLCJwYXlvdXQtd2ViaG9va3M6cmVhZCJdfSwiY29yZSI6eyJyb2xlcyI6WyJyZWZ1bmRzOndyaXRlIiwicmVmdW5kczpyZWFkIiwiY2hlY2tzOndyaXRlIiwiY2hlY2tzOnJlYWQiLCJzcGxpdHM6d3JpdGUiLCJzcGxpdHM6cmVhZCIsInBheW1lbnQtbGlua3M6Y3JlYXRlIiwicGF5bWVudC1saW5rczpyZWFkIiwicGF5bWVudHM6cmVhZCIsImFuYWx5dGljczpyZWFkIiwib3JkZXJzOmNhbmNlbCIsIm9yZGVyczpjcmVhdGUiLCJvcmRlcnM6cmVmdW5kIiwib3JkZXJzOmNhcHR1cmUiLCJvcmRlcnM6cmVhZCIsInN1YnNjcmlwdGlvbnM6d3JpdGUiLCJzdWJzY3JpcHRpb25zOnJlYWQiLCJ3ZWJob29rczp3cml0ZSIsIndlYmhvb2tzOnJlYWQiXX19LCJ1c2VyIjp7ImlkIjoidXNyX1VUTkRYWjJCSE4iLCJkaXNwbGF5X25hbWUiOiJBbGliZWsgLSIsInVzZXJuYW1lIjoiYWxpYmVrYmFrZGF1bGV0QGdtYWlsLmNvbSIsImZpcnN0X25hbWUiOiJBbGliZWsiLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJsYXN0X25hbWUiOiItIiwiZW1haWwiOiJhbGliZWtiYWtkYXVsZXRAZ21haWwuY29tIiwic3RhdHVzIjoiQUNUSVZFIn0sInNob3AiOnsiaWQiOiJzaHBfUEtFS1pKVVZIRiIsIm93bmVyX2lkIjoidXNyX1VUTkRYWjJCSE4iLCJpc19kZWFsZXIiOmZhbHNlLCJiaW4iOiIxMTExMTExMTExMTEiLCJkaXNwbGF5X25hbWUiOiJCb3N0b24gU2Nob29sIiwic3RhdHVzIjoiQUNDRVBURUQiLCJzdWIiOltdfSwibG9jYWxlIjoicnUifQ.ED57l82g1R7GNsQQ4YPJOcUzadp_vO6KrFrmWvUaGO1FEjF9NSm1uxdAAt4qnjx-GYSm5GJBaPGmb5lO7dp20XwkCk5JUYZQHFl6iaADtgvhlN1Smf5nzo4WqxCntjbbx1j8BVJPlzkpagiDBjXQjv9Wj0jY4tiOj5E81tTZS5xWLnO-ZAZV0emP5wplB2k9FpKFsylGOduQLNMDWTRNK9nwIZq3GGnGWA1y8-3MT-RPWtXZ1hXWUzWjQR2YKE5bpwy3RLXtkWOHwQGgUz89FwOKysHMsTvjaTEGHPyM57yoHU5tcsHEPZUcq5_MEXP0obcm4K1ihME7nhY3azmNKg'

# Default settings
BOOTSTRAP5 = {

    # The complete URL to the Bootstrap CSS file.
    # Note that a URL can be either a string
    # ("https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"),
    # or a dict with keys `url`, `integrity` and `crossorigin` like the default value below.
    "css_url": {
        "url": "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css",
        "integrity": "sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx",
        "crossorigin": "anonymous",
    },

    # The complete URL to the Bootstrap bundle JavaScript file.
    "javascript_url": {
        "url": "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js",
        "integrity": "sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa",
        "crossorigin": "anonymous",
    },

    # The complete URL to the Bootstrap CSS theme file (None means no theme).
    "theme_url": None,

    # Put JavaScript in the HEAD section of the HTML document (only relevant if you use bootstrap5.html).
    'javascript_in_head': False,

    # Wrapper class for non-inline fields.
    # The default value "mb-3" is the spacing as used by Bootstrap 5 example code.
    'wrapper_class': 'mb-3',

    # Wrapper class for inline fields.
    # The default value is empty, as Bootstrap5 example code doesn't use a wrapper class.
    'inline_wrapper_class': '',

    # Label class to use in horizontal forms.
    'horizontal_label_class': 'col-sm-2',

    # Field class to use in horizontal forms.
    'horizontal_field_class': 'col-sm-10',

    # Field class used for horizontal fields withut a label.
    'horizontal_field_offset_class': 'offset-sm-2',

    # Set placeholder attributes to label if no placeholder is provided.
    'set_placeholder': True,

    # Class to indicate required field (better to set this in your Django form).
    'required_css_class': '',

    # Class to indicate field has one or more errors (better to set this in your Django form).
    'error_css_class': '',

    # Class to indicate success, meaning the field has valid input (better to set this in your Django form).
    'success_css_class': '',

    # Enable or disable Bootstrap 5 server side validation classes (separate from the indicator classes above).
    'server_side_validation': True,

    # Renderers (only set these if you have studied the source and understand the inner workings).
    'formset_renderers': {
        'default': 'django_bootstrap5.renderers.FormsetRenderer',
    },
    'form_renderers': {
        'default': 'django_bootstrap5.renderers.FormRenderer',
    },
    'field_renderers': {
        'default': 'django_bootstrap5.renderers.FieldRenderer',
    },
}

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
SPECTACULAR_SETTINGS = {
    'TITLE': 'LMS API',
    'DESCRIPTION': 'LMS Project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}