# Generated by Django 4.1.7 on 2024-10-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_network_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
