# Generated by Django 4.1.7 on 2024-11-09 13:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241109_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256, verbose_name='Полное имя')),
                ('position', models.CharField(max_length=100, verbose_name='Специализация')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Profile URL')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Profile URL')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin Profile URL')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter Profile URL')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Телефонный номер')),
                ('geolocation', models.CharField(max_length=40, verbose_name='Местоположение на английском в формате (Kazakhstan, Almaty)')),
                ('accounting', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Accounting Skill From 0 To 100')),
                ('writing', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Writing Skill From 0 To 100')),
                ('speaking', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Speaking Skill From 0 To 100')),
                ('reading', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Reading Skill From 0 To 100')),
                ('about', models.TextField(max_length=1500, verbose_name='About text')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='teacher_images/', verbose_name='Profile Teacher Image')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['fullname'],
            },
        ),
    ]
