# Generated by Django 4.1.7 on 2024-11-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='creator',
            new_name='user',
        ),
    ]
