# Generated by Django 4.1.7 on 2024-11-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_creator_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='about',
        ),
        migrations.AddField(
            model_name='teacher',
            name='about_en',
            field=models.TextField(default='default', max_length=1500, verbose_name='About text English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='about_ru',
            field=models.TextField(default='', max_length=1500, verbose_name='About text Russian'),
            preserve_default=False,
        ),
    ]
