# Generated by Django 4.2 on 2025-03-09 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='xp',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
