# Generated by Django 4.2 on 2025-03-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_level_customuser_xp_alter_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True, verbose_name='Уровень')),
                ('xp_required', models.PositiveIntegerField(verbose_name='Опыт для достижения')),
            ],
            options={
                'verbose_name': 'Настройка уровня',
                'verbose_name_plural': 'Настройки уровней',
                'ordering': ['level'],
            },
        ),
    ]
