# Generated by Django 4.2 on 2025-04-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_levelsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelsetting',
            options={'ordering': ['level'], 'verbose_name': 'Level', 'verbose_name_plural': 'Level settings'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['fullname'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
