# Generated by Django 4.2 on 2025-04-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_levelsetting_options_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='teacher_certificates/', verbose_name='Certificate'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Teacher Approved'),
        ),
    ]
