# Generated by Django 4.2 on 2025-04-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_teacher_certificate_teacher_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='request_code',
            field=models.CharField(default='111111', max_length=6, verbose_name='Request Code'),
            preserve_default=False,
        ),
    ]
