# Generated by Django 4.2 on 2025-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_teacher_request_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quiz_completed',
            field=models.BooleanField(default=False),
        ),
    ]
