# Generated by Django 4.2 on 2025-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_purchase_certificate_file'),
        ('accounts', '0012_customuser_quiz_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recommended_tags',
            field=models.ManyToManyField(blank=True, related_name='recommended_users', to='webapp.tag'),
        ),
    ]
