# Generated by Django 4.2 on 2025-05-05 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_purchase_certificate_file'),
        ('accounts', '0013_customuser_recommended_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('tags', models.ManyToManyField(to='webapp.tag')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='accounts.quizquestion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tag')),
            ],
        ),
    ]
