# Generated by Django 4.2 on 2025-05-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_quizquestion_quizoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizoption',
            name='text_ru',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='text_ru',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
