# Generated by Django 4.1.7 on 2024-11-03 08:21

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Ключ')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('name_kz', models.CharField(max_length=100, verbose_name='Название на казахском')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название на английском')),
                ('text_color', models.CharField(max_length=6, verbose_name='HEX цвет шрифта (цвет отображений на странице блога)')),
                ('background_color', models.CharField(max_length=6, verbose_name='HEX цвет бэкграунда (цвет отображений на странице блога)')),
                ('border_color', models.CharField(max_length=6, verbose_name='HEX цвет обводки (цвет отображений на странице блога)')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=300, verbose_name='Заголовок на русском')),
                ('title_kz', models.CharField(max_length=300, verbose_name='Заголовок на казахском')),
                ('title_en', models.CharField(max_length=300, verbose_name='Заголовок на английском')),
                ('description_ru', models.TextField(blank=True, max_length=350, null=True, verbose_name='Описание на русском')),
                ('description_kz', models.TextField(blank=True, max_length=350, null=True, verbose_name='Описание на казахском')),
                ('description_en', models.TextField(blank=True, max_length=350, null=True, verbose_name='Описание на английском')),
                ('image', models.FileField(upload_to='news/pictures/', verbose_name='Основная картинка поста')),
                ('image_list', models.FileField(blank=True, null=True, upload_to='news/pictures/', verbose_name='Картинка для списка')),
                ('image_mobile', models.FileField(blank=True, null=True, upload_to='news/pictures/', verbose_name='Картинка для мобильной версии')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент на русском')),
                ('content_kz', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент на казахском')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент на английском')),
                ('conclusion_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Выводы на русском')),
                ('conclusion_kz', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Выводы на казахском')),
                ('conclusion_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Выводы на английском')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показать?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('tags', models.ManyToManyField(related_name='posts', to='blog.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
