# Generated by Django 4.1.7 on 2024-11-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conclusion_kz',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_kz',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description_kz',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_kz',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name_kz',
        ),
    ]
