# Generated by Django 4.2 on 2024-11-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_conclusion_kz_remove_post_content_kz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_mobile',
        ),
    ]
