# Generated by Django 4.2 on 2024-11-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conclusion_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='conclusion_ru',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='border_color',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='text_color',
        ),
    ]
