# Generated by Django 4.1.7 on 2024-11-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_teacher_about_teacher_about_en_and_more'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='accounts.teacher', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
    ]
