# Generated by Django 4.1.7 on 2024-11-03 17:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None, verbose_name='ID правильных ответов')),
                ('user_answer_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None, verbose_name='ID ответов пользователя')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завершения')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_histories', to='webapp.test', verbose_name='Тест')),
                ('test_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='webapp.testmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_histories', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История прохождения теста',
                'verbose_name_plural': 'Истории прохождения тестов',
            },
        ),
    ]
