# Generated by Django 4.1.7 on 2024-11-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testhistory',
            unique_together=set(),
        ),
    ]
