# Generated by Django 4.1.7 on 2024-11-03 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_testhistory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='test_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='webapp.testmodule'),
        ),
    ]
