# Generated by Django 4.1.7 on 2024-11-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Preview Description For Course List Page'),
        ),
    ]
