# Generated by Django 4.2 on 2024-11-11 18:51

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='key_takeaway',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Key Takeaway'),
            preserve_default=False,
        ),
    ]
