# Generated by Django 4.1.7 on 2024-11-09 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_course_preview_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Скилл на русском')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Скилл на английском')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='webapp.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Скилл, который можно приобрести на курсе',
                'verbose_name_plural': 'Скиллы, который можно приобрести на курсе',
            },
        ),
    ]
