# Generated by Django 4.2 on 2024-11-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_lesson_key_takeaway'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Position'),
        ),
    ]
