# Generated by Django 4.1.7 on 2024-11-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='Course',
            new_name='course',
        ),
    ]
