# Generated by Django 4.1.7 on 2024-06-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_module_created_at_module_updated_at_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='small_description',
            field=models.TextField(default='small description', max_length=255, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
