# Generated by Django 4.1.7 on 2024-10-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_lessonprogress_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'В ожидании'), ('DONE', 'Оплачено')], default='PENDING', max_length=20),
        ),
    ]
