# Generated by Django 4.1.7 on 2024-11-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_course_skills_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Скилл, который можно приобрести на курсе', 'verbose_name_plural': 'Скиллы, которые можно приобрести на курсе'},
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='name_ru',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='name_en',
        ),
    ]
