# Generated by Django 4.2 on 2025-03-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_code',
            field=models.CharField(default='1111', max_length=6, unique=True, verbose_name='Код оплаты'),
            preserve_default=False,
        ),
    ]
