# Generated by Django 4.2 on 2025-03-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_purchase_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_amount',
            field=models.PositiveIntegerField(default=1000, verbose_name='Сумма оплаты'),
            preserve_default=False,
        ),
    ]
