# Generated by Django 4.1.7 on 2024-10-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_purchase_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Длительность видео'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL превью'),
        ),
    ]
