# Generated by Django 4.1.7 on 2024-11-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_skills_options_rename_name_ru_skills_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('RU', 'Russian')], default='EN', max_length=2, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='course',
            name='skill_level',
            field=models.CharField(choices=[('ALL', 'All Levels'), ('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='ALL', max_length=12, verbose_name='Skill Level'),
        ),
    ]
