# Generated by Django 4.1.7 on 2024-10-29 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0007_lesson_duration_lesson_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
