# Generated by Django 4.1.7 on 2024-10-27 11:49

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_testmodule_test_answeroption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='answer_text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ответ'),
        ),
    ]
