# Generated by Django 4.1.7 on 2024-11-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_answeroption_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_modules', to='webapp.course', verbose_name='Тестовый модуль'),
        ),
    ]
