# Generated by Django 4.2 on 2025-04-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_tag_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
