# Generated by Django 5.1.2 on 2024-11-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_lesson_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Длительность видео'),
        ),
    ]
