# Generated by Django 4.1.7 on 2024-11-02 12:46

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_testmodule_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_descriptions', to='webapp.course', verbose_name='Тестовый модуль')),
            ],
        ),
    ]
