# Generated by Django 5.1.2 on 2024-11-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность видео'),
        ),
    ]
