# Generated by Django 4.2 on 2025-04-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_tag_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcasedescriptions',
            options={'verbose_name': 'Course Tests Description №1', 'verbose_name_plural': 'Course Tests Description №1'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='has_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='webapp.testmodule', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='testcasedescriptions',
            name='title',
            field=models.CharField(default='Заголовок', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='testcasedescriptions',
            name='сourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_descriptions', to='webapp.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='testmodule',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_modules', to='webapp.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='testmodule',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, verbose_name='Лимит времени прохождения (минуты)'),
        ),
        migrations.AlterField(
            model_name='testmodule',
            name='title',
            field=models.CharField(default='Заголовок модуля тестов', max_length=255, verbose_name='Name'),
        ),
    ]
