# Generated by Django 5.1.2 on 2024-11-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_lesson_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
