# Generated by Django 4.1.7 on 2024-11-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_testmodule_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeroption',
            old_name='test',
            new_name='test_id',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='test_module',
            new_name='test_module_id',
        ),
        migrations.RenameField(
            model_name='testcasedescriptions',
            old_name='module',
            new_name='сourse_id',
        ),
        migrations.RenameField(
            model_name='testmodule',
            old_name='module',
            new_name='test_id',
        ),
        migrations.AddField(
            model_name='testcasedescriptions',
            name='title',
            field=models.CharField(default='Default Title', max_length=255, verbose_name='Name'),
        ),
    ]
