# Generated by Django 4.2 on 2025-05-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_testcasedescriptions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Файл сертификата'),
        ),
    ]
