# Generated by Django 4.1.7 on 2024-11-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_rename_test_answeroption_test_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodule',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
