# Generated by Django 4.1.7 on 2024-11-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_testmodule_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodule',
            name='test_id',
        ),
        migrations.AddField(
            model_name='testmodule',
            name='cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test_modules', to='webapp.course', verbose_name='Тестовый модуль'),
            preserve_default=False,
        ),
    ]
