# Generated by Django 4.1.7 on 2024-11-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_remove_testmodule_test_id_testmodule_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodule',
            name='title',
            field=models.CharField(default='New titile', max_length=255, verbose_name='Name'),
        ),
    ]
