# Generated by Django 4.1.7 on 2024-11-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_testmodule_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodule',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, verbose_name='Лимит времени (минуты)'),
        ),
    ]
