# Generated by Django 4.1.7 on 2024-11-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_testmodule_time_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeroption',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='test_module_id',
            new_name='test_module',
        ),
        migrations.RenameField(
            model_name='testcasedescriptions',
            old_name='сourse_id',
            new_name='сourse',
        ),
    ]
