version: '3.8'

networks:
  dev:

services:
  db:
    image: postgres:13
    container_name: postgress
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - dev
    ports:
      - "5482:5432"

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - dev
    ports:
      - "6379:6379"

  web:
    build: .
    command: /bin/bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:9400"
    volumes:
      - .:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles  # 👈 добавляем явный том для collected static
    ports:
      - "9400:9400"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/lms
    depends_on:
      - db
    networks:
      - dev

volumes:
  postgres_data:
